version: '3'
services:
  redis-search:
    image: redislabs/redisearch:2.0.2
    ports:
      - "6379:6379"
  redis-bash:
    image: redislabs/redisearch:2.0.2
    command: bash
    volumes:
      - ./:/usr/src/code
    links:
      - redis-search:redis
  convert-script:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash
    volumes:
      - ./:/app
